### ISSUE TITLE
This is cool, how can i help

### ISSUE THREAD

**Issue by sebirdman** [ajmarks/ajmarks_ha_components#1]
I just wanted to say, great work! Recently bought a GE oven and thought "oh well i don't see any home assistant support so i'll have to reverse engineer this"  and lo, found this. Installation was easy and I can see my oven and some of the stats.

Few questions:
1) i'm not seeing the oven view you've got in the readme for my oven, how can i get that?
2) there's a few additional features that my oven has that i don't see support for: probe temp, cooktop on/off, and maybe a few others i haven't seen yet. What would be the best way to go about trying to help add support for these things?

**Comment by ssaenger** [comment]
I am building a house and will be getting the 30" single, in-wall oven from GE (model #jts5000enes). I want to integrate this oven into HA. I guess I'll have to wait and see when I move in if it has an integration already. However if not, I would like to contribute anyway I can.

**Comment by sebirdman** [comment]
@ssaenger i've been using @simbaja 's fork and it's been working very well in my home.

My only wish is that home assistant had better support for these kinds of devices, using a water heater entity feels very strange still. but it does the job.

**Comment by ajmarks** [comment]
I agree with you completely, but it is what it is.  There's an issue for HA
to add a cooker platform, but it's been open forever.

**Comment by chrisgilldc** [comment]
Good morning! My new home likewise came with GE appliances and have been looking for an integration like this. Going to give it a shot, and while I'm a marginal coder at best, very happy to help with testing. I do have a dishwasher!
